spring:
  application:
    name: gestao-alunos-api
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: admin
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true